# Generated by Django 5.1 on 2025-02-15 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='model',
        ),
        migrations.RemoveField(
            model_name='product',
            name='part_number',
        ),
    ]
