# Generated by Django 5.1 on 2025-02-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_remove_product_model_remove_product_part_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='writer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
