# Generated by Django 5.1 on 2025-02-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_product_writer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='writer_photos/')),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='writer_name',
            new_name='writer',
        ),
    ]
