# Generated by Django 5.1 on 2025-02-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_writer_rename_writer_name_product_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='writer',
        ),
        migrations.AddField(
            model_name='product',
            name='writer',
            field=models.ManyToManyField(to='Product.writer'),
        ),
    ]
