# Generated by Django 5.1 on 2025-02-15 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_remove_product_writer_product_writer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='writer',
            new_name='writers',
        ),
    ]
