# Generated by Django 5.1 on 2025-02-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_rename_writer_product_writers'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
