# Generated by Django 5.2.1 on 2025-05-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='writers',
        ),
        migrations.AddField(
            model_name='product',
            name='writers',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
