# Generated by Django 5.2 on 2025-04-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_description',
            field=models.CharField(default='No description yet', help_text='A short summary (30-40 characters).', max_length=100),
        ),
    ]
